### ISSUE TITLE
使用UIAlert发布后报错

### ISSUE THREAD

**Issue by jinda** [qilinshuyuan/OpenTGX#5]
使用UIAlert弹窗报错，在debug模式没有问题，发布出web-destop运行就报如下错，日志输出this是有_layout的，但是this.layout就是undefine值。
TypeError: Cannot read properties of undefined (reading 'btnOK')
    at o.onCreated (index.c716f.js:71:2343)
    at n.setup (index.c716f.js:73:1935)
    at index.c716f.js:81:2627
    at _virtual_cc-37716973.js:1:463042
    at _virtual_cc-37716973.js:1:29414
    at i (_virtual_cc-37716973.js:1:29379)
解决办法注释掉UIAlert中的public get layout()方法 ~~~

**Comment by MrKylinGithub** [comment]
已修复
